### ISSUE TITLE
git2r 0.10.1 breaks support for windows XP

### ISSUE THREAD

**Issue by justa9** [ropensci/git2r#139]
Hello.

The latest version of git2r (0.10.1) does not work on windows XP.
An error window pops up stating "the procedure entry point _chsize_s could not be located in msvcrt.dll". There is some discussion on the message in this sourceforge thread: 
http://sourceforge.net/p/mingw-w64/mailman/message/29616501/

Unfortunately this means that package devtools also does not work on windows XP anymore.

**Comment by jrminter** [comment]
I confirm. Any way to get an older Windows binary as a workaround?

**Comment by stewid** [comment]
`git2r` is an interface to the [libgit2](https://libgit2.github.com/) library. Since `libgit2` dropped support for Windows XP with the [v0.21.0](https://github.com/libgit2/libgit2/releases/tag/v0.21.0) release, `git2r` can not support Windows XP.

@jrminter you only need zlib on Windows, no need for openssl. If you have installed Rtools and configured [LOCAL_SOFT](http://www.stats.ox.ac.uk/pub/Rtools/libs.html), it should work to install with:

```
git clone https://github.com/ropensci/git2r.git
cd git2r
make
```

**Comment by benmarwick** [comment]
For what it's worth, I installed git2r from github on Windows 7 yesterday using the instructions here: https://github.com/ropensci/git2r/issues/95 For older windows (assuming 64bit) I'd suggest using rocker to get a linux vm.

**Comment by jrminter** [comment]
Thanks for the information. I'll give it a try.

**Comment by justa9** [comment]
@stewid  Thank you for the helpful information. I successfully installed the older version git2r (0.7) on XP by following the instructions.

**Comment by stewid** [comment]
@justa9 Thanks for testing version 0.7 on XP and reporting back.

**Comment by stewid** [comment]
It should no longer be necessary to configure LOCAL_SOFT to build `git2r` on Windows. The configuration has been improved to automatically download `local320.zip` and extract the `zlib` files if
they are not found in LOCAL_SOFT, see [configure.win](https://github.com/ropensci/git2r/blob/master/configure.win) for details.
