### ISSUE TITLE
Release planning

### ISSUE THREAD

**Issue by jennybc** [ropensci/git2r#347]
usethis will have a small release soon and I want to address any obvious and tractable problems re: usethis/git2r, such as switching over to `git2r::repository_head(r)`. I'd rather not write conditional code, i.e. I'd prefer to just require a current version of git2r.

Is this realistic or are you fairly far away from a CRAN release?

**Comment by stewid** [comment]
I don't have enough time right now to work on git2r. There are two issues that make it difficult to submit a release. First the build configuration on macOS must be improved to address the CRAN check warning. My plan is to refactor the configuration so that libgit2 is installed using the brew package manager instead of using the bundled libgit2. Secondly, something in the refactoring to S3 classes is causing the 'Invalid repository' error on Windows (#329) but I have not been able to reproduce it.

**Comment by jennybc** [comment]
Our r-lib/tidyverse team would like to help out then, if that would be welcome.

Do you have any more concrete details or links to share re: the macOS issue? @jimhester indicates he can look into this.

I think the info available for #329 is fairly clear.

@jeroen Can you be tempted into this effort at all? Can you reproduce #329? I cannot on my VM but it's obviously a real problem.

**Comment by jeroen** [comment]
@stewid I can help refactoring to unbundle libgit2 and use the system version instead, like we do for most packages. Are you using libgit2 api calls that are not available on system installations?

**Comment by stewid** [comment]
> Our r-lib/tidyverse team would like to help out then, if that would be welcome.

Thanks, much appreciated.

> Do you have any more concrete details or links to share re: the macOS issue? @jimhester indicates he can look into this.

CRAN has the following check warning (https://cran.r-project.org/web/checks/check_results_git2r.html).

```
Version: 0.21.0
Check: whether package can be installed
Result: WARN
    Found the following significant warnings:
     openssl.c:420:31: warning: incompatible pointer types assigning to 'int (*)(EVP_CIPHER_CTX *, unsigned char *, const unsigned char *, unsigned int)' (aka 'int (*)(struct evp_cipher_ctx_st *, unsigned char *, const unsigned char *, unsigned int)') from 'int (EVP_CIPHER_CTX *, unsigned char *, const unsigned char *, size_t)' (aka 'int (struct evp_cipher_ctx_st *, unsigned char *, const unsigned char *, unsigned long)') [-Wincompatible-pointer-types]
Flavor: r-release-osx-x86_64
```
which happens during the build of libssh2.

One challenge is that each release of `libgit2` has so far had breaking API changes (https://github.com/libgit2/libgit2/releases). The development version of `git2r` bundles the latest libgit2 version (v0.27 released Mar 26). Since various package managers contains different version of libgit2, I think that git2r must continue to bundle libgit2 but that the configuration could be improved to only use it if necessary. For example, the brew package manager contains v0.27 of libgit2 https://formulae.brew.sh/formula/libgit2.

> Are you using libgit2 api calls that are not available on system installations?

No, since the latest commit (e2b36029db0c279d7e92924fc0eb698bdb5ab45c) it should be possible to link against a system installation of libgit2 (v0.27). Maybe it's simplest to first try this on Windows?

Thanks

**Comment by jeroen** [comment]
OK here is a PR that switches to the rwinlib verion of libgit2: https://github.com/ropensci/git2r/pull/348. This makes the build a lot easier and enables all libgit2 features on Windows.

Can you test if this also fixes https://github.com/ropensci/git2r/issues/329?

**Comment by stewid** [comment]
I have done more refactoring of the configuration to use libgit2 from brew on macOS

**Comment by jennybc** [comment]
What do you think needs to happen re: validating the macOS changes? Or is that perhaps overstating where things are? If there are instructions, I'd be willing to try them.

**Comment by stewid** [comment]
It remains to handle the case when brew is missing. My plan is to copy the `autobrew` solution by @jeroen . I think we need to write instructions and test that it works with https and ssh. @jennybc  do
you think it's possible to have tests on travis with push/clone operations over https/ssh?

**Comment by jennybc** [comment]
> @jennybc do you think it's possible to have tests on travis with push/clone operations over https/ssh?

I'm sure it's possible but I haven't done it. I suppose we would need a dummy account for this.

**Comment by stewid** [comment]
I will submit version 0.22 to CRAN on Monday 9 July.
