### ISSUE TITLE
Version 0.31.0 does not build on Debian

### ISSUE THREAD

**Issue by tillea** [ropensci/git2r#445]
Hi,
I intended to update the Debian package of git2r to the latest upstream version 0.31.0 but the build failed with:

    libgit2/src/unix/posix.h:35:3: error: #error GIT_USE_NSEC defined but unknown struct stat nanosecond type
       35 | # error GIT_USE_NSEC defined but unknown struct stat nanosecond type
          |   ^~~~~

You can find a [full build log](https://salsa.debian.org/r-pkg-team/r-cran-git2r/-/jobs/3882052) in the Debian CI.
Kind regards, Andreas.

**Comment by stewid** [comment]
Thanks for reporting this.

**Comment by jeffkeller87** [comment]
I get the same error when installing from source on Kubuntu 22.04.1.

**Comment by stewid** [comment]
`git2r` can be built with a system installation of libgit2 instead of using the bundled source of libgit2. Therefore, it should work if you first install `libgit2-dev` on Debian and Ubuntu. That might also be a better approach for packaging `git2r`? Could you please try to install `git2r` after installing `libgit2`?

**Comment by jeffkeller87** [comment]
Confirmed, I can install `git2r` from source on Kubuntu 22.04.1 after installing `libgit2-dev`.

**Comment by tillea** [comment]
Am Thu, Feb 02, 2023 at 05:23:11PM -0800 schrieb Jeff Keller:
> Confirmed, I can install `git2r` from source on Kubuntu 22.04.1 after installing `libgit2-dev`.
Thanks for the hint.  r-cran-git2r is now build against libgit2-dev.  Andreas.

**Comment by stewid** [comment]
Thanks
